### PR TITLE
Delimit arguments by space too

### LINKED ISSUE #59: chrome-flags.conf not working
Hi there!

I'm trying to run Brave using Ozone/Wayland.

If I understood correctly the cobalt settings, I can pass flags to brave by setting the file:

`~/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/chrome-flags.conf`

with this content:

`--enable-features=UseOzonePlatform --ozone-platform=wayland`

That should be enough, right? It's not picking them for me. I'm checking `brave://version/` to see if the flags are passed

### PR DESCRIPTION
**Pull request by rany2**
Fix https://github.com/flathub/com.brave.Browser/issues/59#issuecomment-888567484

### CODE REVIEW

**Comment by refi64** [comment]
Thanks for this! As-is, however, it seems like it'll switch to *only* splitting by spaces, dropping newline support?

I think you could look into using `g_shell_parse_argv`, which should split by both spaces *and* newlines, as well as adding quoting support (if you, for some reason, needed a space or similar in an argument). This...might actually support comment & blank line handling for us too(?), which would incidentally fix the blank line issue too. (I'm not actively at a computer, though, so I can't really test this.)

**Comment by rany2** [comment]
@refi64 It will not drop new line support. Both will work fine

**Comment by rany2** [comment]
@refi64 I just got access to my personal machine and replaced strtok with g_shell_parse_argv as you suggested.

> as well as adding quoting support (if you, for some reason, needed a space or similar in an argument). This...might actually support comment & blank line handling for us too(?), which would incidentally fix the blank line issue too. (I'm not actively at a computer, though, so I can't really test this.)

Yes, I just tested this. It works like this!

File: src/cobalt-launcher.c [hunk 1]
```diff
@@ -112,23 +112,36 @@ gboolean cobalt_launcher_read_flags_file(CobaltLauncher *launcher, GFile *file,
...
     }
 
-    if (g_str_has_prefix(line, ENABLE_FEATURES_FLAGFILE_PREFIX) ||
-        g_str_has_prefix(line, DISABLE_FEATURES_FLAGFILE_PREFIX)) {
-      const char *feature = strchr(line, '=') + 1;
-      if (*feature == '\0') {
-        g_warning("Line in '%s' has an empty feature: %s", g_file_peek_path(file), line);
+    {
+      gint tokenc;
+      gchar **tokenv;
```
Comment (refi64) [inline src/cobalt-launcher.c]: This will leak the tokens after this finishes, you can make this `g_auto(GStrv) tokenv = NULL;` instead to "fix" that.

File: src/cobalt-launcher.c [hunk 2]
```diff
@@ -112,23 +112,36 @@ gboolean cobalt_launcher_read_flags_file(CobaltLauncher *launcher, GFile *file,
...
+      gboolean ret;
+
+      ret = g_shell_parse_argv (line, &tokenc, &tokenv, NULL);
+      if (!ret) {
+        return FALSE;
```
Comment (refi64) [inline src/cobalt-launcher.c]: It seems a bit extreme to die parsing the full file, you could probably just `g_warning`, basing it off of some of the uses below, and using a `g_autoptr(GError) local_error = NULL` and passing that would allow us to get the error message (you can also base this off of some of the other uses in the source code). (It may also be a bit cleaner to inline the value of `ret` into the `if`, instead of saving it separately.)

File: src/cobalt-launcher.c [hunk 3]
```diff
@@ -112,23 +112,36 @@ gboolean cobalt_launcher_read_flags_file(CobaltLauncher *launcher, GFile *file,
...
-      g_warning("Line in '%s' is not a flag (must start with '--'): %s",
-                g_file_peek_path(file), line);
-    } else {
-      cobalt_launcher_add_arg(launcher, line);
+      for (int i = 0; i < tokenc; i++) {
+        if (g_str_has_prefix(tokenv[i], ENABLE_FEATURES_FLAGFILE_PREFIX) ||
+            g_str_has_prefix(tokenv[i], DISABLE_FEATURES_FLAGFILE_PREFIX)) {
+          const char *feature = strchr(tokenv[i], '=') + 1;
+          if (*feature == '\0') {
+            g_warning("Argument in '%s' has an empty feature: %s", g_file_peek_path(file), tokenv[i]);
```
Comment (refi64) [inline src/cobalt-launcher.c]: Any chance you could run this through `clang-format`? I believe some of these lines are now above the line width and need reformatting.

**Review by refi64 — CHANGES_REQUESTED** [review]
Almost there, just a few minor nits remaining. Also:

> It will not drop new line support.

Whoops my bad, I really need to stop this do-code-reviews-while-late-and-distracted thing :sweat_smile:

File: src/cobalt-launcher.c (hunk 1 above)
Comment (rany2) [reply src/cobalt-launcher.c]: Wouldn't putting it in its own scope prevent it from leaking tokens?
